name: Dockerize 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t keycloak-app .
